
const BACKGROUND_BLACK = "#0D0C1D";
const BACKGROUND_RED = "";
const BACKGROUND_WHITE = "#EFFFFA";
const LINK_DARK = "#343078"
const TEXT_BACK = "";
const TEXT_WHITE = "";


export { BACKGROUND_BLACK, BACKGROUND_RED,  BACKGROUND_WHITE, LINK_DARK, TEXT_BACK, TEXT_WHITE}